baseURL = 'https://telzhou618.github.io'
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "Home"
# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FixIt"

[menu]
[[menu.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 1
[[menu.main]]
  name = 'Archives'
  pageRef = '/archives'
  weight = 2
[[menu.main]]
  name = 'Categories'
  pageRef = '/categories'
  weight = 3
[[menu.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 4
[[menu.main]]
  name = 'About'
  pageRef = '/about'
  weight = 5

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    ########## necessary configurations ##########
    # https://github.com/hugo-fixit/FixIt/issues/43
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    ########## necessary configurations ##########
    guessSyntax = true
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    ordered = false
    startLevel = 2
    endLevel = 6

[outputs]
  home = ["HTML", "RSS", "JSON", "archives"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML", "RSS"]

# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

[params]
  # FixIt theme version
  version = "0.3.X" # e.g. "0.2.X", "0.2.15", "v0.2.15" etc.
  # ...


