baseURL = 'https://telzhou618.github.io'
languageCode = 'en-us'
title = 'Home'
theme = "paper"

[menu]
[[menu.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 10
[[menu.main]]
  name = 'About'
  pageRef = '/about'
  weight = 20

# [taxonomies]
#   category = "categories"
#   tag = "tags"

# disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments
[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light
  # header social icons
#   twitter = 'https://github.com/telzhou618'               # twitter.com/YOUR_TWITTER_ID
  github = 'telzhou618'                 # github.com/YOUR_GITHUB_ID
#   instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
#   linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
#   mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
#   rss = true                                # show rss icon

  # home page profile
  avatar = 'https://s.gravatar.com/avatar/9ff9514e4c37a5cb11be475190289857778d613942c4d6364c16e770a4cb66a0?s=80'                 # gravatar email or image url
  name = 'telzhou618'
  bio = 'java'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  graphCommentId = "a42bc435-1a67-9bc8-2cde-72ec7ba0d2fb"  # use graph comment (disqus alternative)
  comments = true
  math = true                               # enable KaTex math typesetting globally
